name: Continuous Integration

on:
  
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install APT dependencies
      run: sudo apt install libgtest-dev build-essential cmake
      
    - name: Build and install GTest
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo cmake --build . --target install
        
    - name: Build tests
      run: |
        cmake -DBUILD_TESTING=ON .
        make
        
    - name: Run tests
      run: ./NexusTest
